"""
Metin üretimi
lstm train with data
text data = gpt ile oluşturulmuştur.
""" 

#import library
#eğitim verisini oluşturma
#tokenizasyon
#ngram dizileri oluştur ve padding uygula
#metin temizleme ve preprocessing:  tokinization, padding, laben encoding,train text split
#lstm modeli oluştur: compile, train, evaluate
#model prediction

#---------------------------------
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential   # base model, lstm dense embeding işlemlerini eklicez
from tensorflow.keras.layers import LSTM, Dense, Embedding   # katmanlar
from tensorflow.keras.preprocessing.text import Tokenizer   #token işlemini yapmak için
from tensorflow.keras.preprocessing.sequence import pad_sequences  # padding işlemi için




texts = [
    "Gözlerimde kaybolan güneşin ışıkları, kalbimi aydınlatıyor; her ışık huzmesi bir umut gibi.",
    "Rüzgarın taşıdığı melodiyi dinlerken, kuşların dansı bana özgürlüğün anlamını hatırlatıyor.",
    "Bazen bir çiçek, karanlık günlere umut olur; toprağa düşen her damla, sevdanın izini bırakır.",
    "Gökyüzündeki yıldızlar birer dilek gibi parlıyor, her biri bir öykü anlatıyor, geceye düşen sessiz yankılarla.",
    "Bir yağmur damlası, kalbimdeki kuraklığı siler, her damla bir dilek, her gölet bir hayal olur.",
    "Denizin fısıldadığı sırlar, dalgaların öyküsünde kaybolan bir hayatın izlerini taşır.",
    "Bazen bir an, zamanın ötesine geçer; sonsuzluğa ait bir saniye, kalbin derinliklerinde yankı yapar.",
    "Bir ağacın dallarından düşen yaprak, rüzgarın eşliğinde bir yolculuğa çıkar; sonbahar, geçmişin hatıralarına dokunur.",
    "Gecenin sarhoşluğunda, ay ışığına sarılan bir ruh, uykusuzluğun huzurunda kaybolur.",
    "Bir çiçeğin açışı, bir düşün gerçeğe dönüşüdür; hayal, yerini gerçeğe bırakır, rüzgar her iki yolda da dans eder.",
    "Beyaz bulutlar, gökyüzünde sevdanın izini bırakırken, kalbimde sessiz bir şarkı çalmaya başlar.",
    "Bir an, göğüs kafesimden çıkıp, rüzgarın kanatlarında kaybolan bir kuş gibi, özgürlüğe adım atarım.",
    "Geceyi sarıp sarmalayan karanlık, yıldızların parıltısı altında bir masal gibi içime işler.",
    "Bir çiçeğin solan yaprağı, hayatın geçici olduğunu hatırlatırken, yeni umutlar filizlenir her köşede.",
    "Bazen bir yıldız kayar, dilekler düşer; o an tüm evren, bir nefes gibi derinleşir.",
    "Bir rüzgarın dokunuşu, tenimde bir melodi gibi çalar, gönlümde hüzünle karışan bir neşe bırakır.",
    "Bir gece daha geçerken, ayın gizemli ışığı, geçmişin hatıralarını siler, bana sadece şimdiyi bırakır.",
    "Bir deniz dalgası, sabah güneşiyle buluşurken, yeni bir başlangıcın umut dolu mesajını taşır.",
    "Bir düşün peşinden gitmek, bazen karanlık bir ormanda kaybolmak gibidir, ama sonunda ışık vardır.",
    "Bir yaprağın düşüşü, bir hayatın son bulması ve yeni bir hayata doğuşu arasında bir köprü kurar.",
    "Gözlerimde kaybolan yıldızlar, kalbimde umutla parlayan bir sevdanın izini bırakır.",
    "Bir anın içindeki sonsuzluğu hissederken, dünya dönmeye devam eder, ama ben sadece o anın içinde kaybolurum.",
    "Bir kuşun özgürce uçtuğu gökyüzü, tüm engelleri aşabilmenin mümkün olduğunu fısıldar.",
    "Bir çiçek, kurak toprakta filizlenirken, bir umut ışığı doğar, karanlıkları arar ve büyür.",
    "Ay ışığının denize yansıması, iki dünyanın birleşmesi gibidir; denizin derinliklerinden, gökyüzüne yükselir.",
    "Bir zamanlar kaybolmuş olan gökkuşağı, şimdi tekrar doğar, her renginde bir umut taşır.",
    "Bazen bir düş, bir yaşamın içinden kayıp gitmek gibidir; ama düşler gerçek olur, kanatlarını açtığında.",
    "Bir kuşun sesi, geceyi aydınlatırken, sessizliğin içindeki melodiyi duymak, ruhumu dinlendirir.",
    "Bir yıldız kayar, dilekler düşer; ama ben sadece evrenin sonsuzluğunda kaybolurum.",
    "Gecenin içinde kaybolan bir yelkenli gibi, her düşünceyi rüzgarla savurur, sadece huzuru ararım.",
    "Bir kumsalda yalnız yürürken, denizin sesini içimdeki huzurla birleştiririm, kalbim biraz daha hafifler.",
    "Bir güneş batışı, günü tamamlayan bir öykü gibidir; her gece, yeni bir başlangıcın umudunu taşır.",
    "Bir yağmurun sesi, toprağa dokunan her damla, içimdeki kırık kalbinizi sarar, yeniden umutla büyür.",
    "Bir ay ışığı, karanlık bir ormanda yol gösteren bir yıldız gibi, beni doğru yola taşır.",
    "Bazen, sadece bir çiçeğin kokusu bile, içimdeki karmaşayı giderir ve bana huzuru getirir.",
    "Bir yıldız, gecenin derinliklerinde kayarken, bir dilek bende yaşam bulur, umutla parlar.",
    "Bir yaprağın düşüşü, hayatın geçici olduğunu hatırlatırken, yeniden doğmanın umudunu taşır.",
    "Bir yağmur damlası, sevdanın içindeki kırılganlığı simgeler, her damla bir anı, bir hatıra bırakır.",
    "Bir kuşun sabahı selamlayışı, hayatın ne kadar değerli olduğunu hatırlatır; her yeni gün, bir şans daha sunar.",
    "Bazen bir anın içinde kaybolurum, ama bir çiçek açtığında, kalbim yeniden uyanır ve hayatı daha derinlemesine hissederim.",
    "Bir akşam, ay ışığının dansı beni sarar, içimdeki tüm karanlıklar silinir, yalnızca huzur kalır.",
    "Bir şarkı, ruhumda yankı bulur; her melodisi, geçmişin duygularını hatırlatır, geleceğin umutlarını taşır.",
    "Bir sabah, yeni umutlarla doğar; her güneşin ışığı, yeni başlangıçların müjdesidir.",
    "Bir yaprağın rüzgarda süzüldüğü an, hayatın ne kadar güzel olduğunu hatırlatır; her şey bir dengeye oturur.",
    "Bir ağaç gölgesinde dinlenmek, dünyanın gürültüsünden uzaklaşmak gibidir; doğanın özüne dokunmak.",
    "Bir yıldız kayar, dilekler düşer; ama aslında her şey içimde bir yerlerde hep var olmuştur, kaybolmaz.",
    "Bir kuşun uçarak gittiği uzaklar, beni kendi özgürlüğüme davet eder, her bir kanat çırpışıyla hayata yeniden başlarım.",
    "Bir orman yolunda yürürken, her adımda kaybolan düşüncelerim, sessizliğin içindeki huzura adım atar.",
    "Bir çiçek açar, sonsuz gökyüzü ona sarılır; her bir yaprak, bir dileğin yansımasıdır.",
    "Bir sabah uyanmak, karanlık gecenin içindeki ışığı görmek gibidir; her yeni gün, yeni umutlar taşır."
    "Bir okyanus üzerinde tek başına yelken açmak, tüm zorlukları aşarak özgürleşmek gibi.",
    "Bir bilim fuarına katılmak, yenilikçi fikirlerle tanışmak beni heyecanlandırıyor.",
    "Gün batımını izlerken bir kavşağa gelmiş gibi hissediyorum; her şey dönüp değişiyor.",
    "Bir ormanın derinliklerine doğru bir keşif yapmak, bilinmeyenlere adım atmanın heyecanını yaşamak.",
    "Bir kitap okurken, sayfalarda kaybolmak, kendimi farklı dünyalarda bulmak gibidir.",
    "Bir köyde bağ bozumu yapmak, doğanın taptaze havasını solumak muazzam bir deneyim.",
    "Bir konserin ön sıralarında olmak, müziği vücudumda hissedip, ruhumu dinlendirmek için en iyi yer.",
    "Yüksek dağlara tırmanmak, her adımda zirveye yaklaşmak, biraz daha özgürleşmek gibi.",
    "Farklı kültürlerin yemeklerini tatmak, dünya üzerindeki çeşitliliği bizzat deneyimlemek çok özel bir şey.",
    "Bir su altı dünyasına dalmak, rengarenk balıkların arasında kaybolmak, doğanın derinliklerine inmeyi seviyorum.",
    "Bir çiçek bahçesinde vakit geçirmek, rengarenk çiçeklerin arasında kaybolmak ve doğanın özünü hissetmek.",
    "Bir ekolojik yaşam alanında yaşamak, sürdürülebilirliği deneyimlemek hayatımın en güzel adımlarından biri.",
    "Bütün günü açık havada geçirmek, doğanın dinlendirici etkisini hissetmek, bedensel ve ruhsal rahatlama sağlamak.",
    "Birçok dilde şarkılar söylemek, dilin müziğini anlamak harika bir deneyim.",
    "Bir bisikletle şehir keşfine çıkmak, her köşede yeni bir şey görmek, keşfetmek heyecan verici.",
    "Bir doğa fotoğrafçısı olarak, anı yakalamak ve her bir kareyle zamanı dondurmak.",
    "Bir müzik aleti çalmayı öğrenmek, her notada ruhumu bulmak ve kendimi ifade etmek.",
    "Bir arkadaşla beraber uzun bir yürüyüşe çıkmak, doğanın huzurunda konuşmak ve sessizlikte rahatlamak.",
    "Bir tatilde hiçbir plan yapmadan gitmek, sadece anı yaşamak ve sürprizlere açık olmak.",
    "Daha fazla dil öğrenmek, dünyadaki farklı insanlarla bağ kurmanın ve daha derin bir anlayışın kapılarını açmak.",
    "Bir çöl safarisi yapmak, kum tepelerinin arasında kaybolmak, sonsuzluk hissine kapılmak harika bir deneyim.",
    "Bütün günü el yazısıyla yazı yazarak geçirmek, kelimelerle düşüncelerimi kağıda dökmek çok anlamlı bir şey.",
    "Bir gece kamp ateşi etrafında arkadaşlarla sohbet etmek, doğanın sessizliğinde birlikte olmanın keyfini yaşamak.",
    "Bir müzik grubuyla sahne almak, müziğin enerjisiyle insanlara dokunmak, performansın zirvesinde olmak.",
    "Bir dilde tam anlamıyla anadil seviyesinde konuşmak, dilin yapısına tamamen hâkim olmak bir hayal.",
    "Yüksek sesle şarkı söylemek, tüm dünyayı unutarak müziğin ruhumda yankı bulmasını sağlamak.",
    "Bir uçakla dünyanın farklı köylerine seyahat etmek, her yeni yeri ve insanı tanımak heyecan verici.",
    "Bir sanat galerisi gezmek, her tablonun derinliğine inmek ve sanatla yeni bir bağ kurmak.",
    "Göl kenarında yürümek, suyun huzur verici sesini dinlemek, etrafınızdaki doğayı tamamen hissetmek.",
    "Bir tiyatro oyununda rol almak, farklı karakterlere bürünmek, sahnede kendimi tamamen kaybetmek.",
    "Bir sabah erkenden uyanıp, kuşların cıvıltısı ile güne başlamak, doğanın uyanışını izlemek büyüleyici.",
    "Kendi bahçemde organik sebzeler yetiştirmek, doğayla iç içe olmanın huzurunu yaşamak.",
    "Bir tatilde okyanus kenarında, dalgaların kıyıya vurmasını dinleyerek dinlenmek.",
    "Bir dans gösterisi izlemek, hareketlerin müziğe nasıl adapte olduğunu görmek büyüleyici.",
    "Bir bisikletle dağ yollarını keşfetmek, doğanın içinde kaybolmak ve her virajda yeni bir şey öğrenmek.",
    "Bir kayak tatilinde zirvelerden aşağı doğru kaymak, karla kaplı dağlarda özgürlüğü hissetmek.",
    "Bir çatı katında sadece geceyi izleyerek sabaha kadar kitap okumak, hayatın hızından uzaklaşmak.",
    "Bir hayvanın bakışlarından duygularını anlamak, onların dünyasına bir adım daha yaklaşmak çok anlamlı.",
    "Yıldızlar altında kamp yapmak, gökyüzündeki derinliği hissederek doğanın büyüsüne kapılmak.",
    "Bir çiftlikte sabah erken saatte sabah çayı içmek ve doğanın uyanışını izlemek çok huzurlu bir deneyim.",
    "Bir çadırda yalnız başıma uyumak, doğanın en derin seslerini dinlemek, rahatlamanın en güzel yolu.",
    "Bir sahil köyünde sakin bir hafta sonu geçirmek, denizle iç içe olmak ve her şeyden uzaklaşmak.",
    "Bir meditasyon öğretmeniyle içsel yolculuğa çıkmak, zihnimi temizlemek ve tamamen huzura kavuşmak.",
    "Bir kitapçıyı gezmek, yeni çıkanları incelemek ve kaybolduğum sayfalarda farklı dünyalar keşfetmek.",
    "Bir tatilde sabah yürüyüşleri yaparak doğanın büyüsünü hissetmek, çevremdeki her şeyi gözlemlemek.",
    "Bambaşka bir kültürde yemek pişirmek, geleneksel tarifleri öğrenmek ve başka bir dünyada yemek yapmak.",
    "Bir tırmanış parkurunda dırma tırmanmak, zihinsel ve fiziksel sınırlarımı keşfetmek.",
    "Bir dağ zirvesinde yalnız başıma güneşin doğuşunu izlemek, özgürlüğün ve doğanın birleşmesi.",
    "Bir tarih gezisi yapmak, farklı medeniyetlerin izlerini sürmek ve geçmişin öğretilerini almak.",
    "Bir film izlerken, oyuncuların her hareketinin anlamını çözmeye çalışmak, sinemayı farklı bir açıdan görmek.",
    "Bir şelalenin dibinde bir yürüyüş yapmak, suyun gürültüsünü ve doğanın dinlendirici etkisini hissetmek.",
    "Bir müze gezisi yapmak ve sanatsal eserlerin dilini anlamak, tarihle iç içe bir yolculuk.",
    "Bir yaz sabahında denize girmek, suyun serinliğiyle yenilenmek ve yazın tadını çıkarmak.",
    "Bir arkadaşla açık hava sinemasına gitmek, geceyi yıldızların altında film izleyerek geçirmek.",
    "Bir denizaltı turuna çıkmak, okyanusun derinliklerine dalmak ve su altı dünyasının mucizelerini görmek.",
    "Bir tiyatro sahnesinde drama yaşamak, sesimi duyurmak ve izleyicilere dokunmak.",
    "Bir ressam gibi tuvalime duygularımı yansıtmak, sanatı kişisel bir ifade biçimi olarak kullanmak.",
    "Bir doğa rezervinde sakin bir gün geçirmek, yalnızlık ve huzur içinde olmak.",
    "Bir yaz akşamı yakın arkadaşlarla dışarıda vakit geçirmek, sıcak yaz rüzgarını hissetmek.",
    "Bir kayıkla gölde gezmek, suyun sakinliğinde kaybolmak ve denizin rahatlatıcı etkisini yaşamak.",
    "Bir araştırma yapmak, bilim dünyasında yeni keşiflerde bulunmak ve insanlığa faydalı olmak.",
    "Bir çok farklı mutfağı öğrenmek ve dünya mutfaklarında ustalaşmak.",
    "Bir film çekiminde yer almak, setin içinde bir hikayenin canlı bir parçası olmak.",
    "Bazen sabah erken saatte kalkıp, yalnız başıma sadece kahvemi içip düşüncelere dalmak.",
    "Farklı bir şehirde sadece yürüyerek gezinmek, her sokağın kendine ait bir hikayesi olduğunu keşfetmek.",
    "Bir konserin atmosferinde kaybolmak, müziği tüm bedenimle hissetmek."
    "Daha önce hiç gitmediğim bir müzik festivaline katılmak istiyorum.",
    "Yıldızlar hakkında daha fazla şey öğrenmek bana her zaman ilham veriyor.",
    "Bir orman içinde sabah yürüyüşü yapmak, güne taze bir başlangıç yapmamı sağlıyor.",
    "Bir hobi olarak ahşap oymacılığına başlamak çok heyecan verici.",
    "Bir restoranın mutfağında şef olmak, yemek yapma tutkumun zirvesine ulaşmak olurdu.",
    "Küçük bir köyde organik tarım yapmak ve doğayla uyum içinde yaşamak çok cazip.",
    "Yeni bir dans stilini öğrenmek, bedenimi daha iyi hissettirmemi sağlıyor.",
    "Bir dilde akıcı olmak, o kültüre daha yakın hissetmemi sağlıyor.",
    "Bir dergide yazı yazmak, kelimelerle dünyamı paylaşmak demek.",
    "Klasik müzik konserlerine gitmek, ruhumu derinlemesine dinlendiriyor.",
    "Yapay zeka ve makine öğrenmesi üzerine çalışmak, geleceği şekillendirme yolunda adım atmak gibi.",
    "Bir film senaryosu yazmak, yaratıcı hayal gücümü anlatmanın en güzel yolu.",
    "Bir hayvan barınağında gönüllü çalışmak, başkalarına yardım etmenin bana kattığı değer.",
    "Bir denizaltı keşif gezisine katılmak, okyanusun derinliklerini görmek heyecan verici.",
    "Eski fotoğrafları dijitalleştirmek ve tarihi korumak, geçmişle bağlantı kurmanın harika bir yolu.",
    "Dağcılık yapmak ve yüksek zirvelere tırmanmak, kendi sınırlarımı aşmamı sağlıyor.",
    "Bir roman yazmaya başlamak, içimdeki hikayeleri dünyaya sunma isteğimi yansıtıyor.",
    "Yoga yaparak zihnimi ve bedenimi dengelemek, kendimi daha huzurlu hissediyorum.",
    "Gece gökyüzünü izlerken astronomi hakkında daha fazla şey öğrenmek büyüleyici.",
    "Birçok farklı mutfaktan yemek tarifleri denemek, tat duyumu keşfetmemi sağlıyor.",
    "Çevre dostu bir yaşam sürmek için evimde sıfır atık uygulamalarına başlamak.",
    "Bir dil öğrenme sürecini başlatmak ve farklı aksanları keşfetmek oldukça ilgi çekici.",
    "Bir tarihi kaleyi gezmek, geçmişin izlerini hissetmek beni büyülüyor.",
    "Kuş gözlemi yaparak doğa hakkında daha fazla bilgi edinmek ve sakinleşmek.",
    "Bir yaz kampında çocuklara doğayı tanıtmak ve eğitici aktiviteler düzenlemek.",
    "Kendi bilgisayarımı inşa etmek, teknolojiyle daha yakın bir bağ kurmamı sağlıyor.",
    "Yeni bir seyahat rehberi yazmak, gezdiğim yerlerdeki gizli cennetleri keşfetmemi sağlayacak.",
    "Bir dilde anadil seviyesinde konuşmak, o dilin inceliklerini tamamen anlamama yardımcı oluyor.",
    "Buz pateni yapmayı öğrenmek, kışın soğuk havasında eğlenceli bir aktivite.",
    "Bir tabiat parkında gece yürüyüşü yapmak, yıldızlar altında kaybolmak harika bir deneyim.",
    "Kendi el yapımı seramiğimi yaratmak, sanatla iç içe olmanın keyfini yaşatıyor.",
    "Bir botanik bahçesinde vakit geçirmek, doğanın çeşitliliğini görmek çok huzur verici.",
    "Bir müze rehberi olmak, tarihin içinde bir yolculuğa çıkmak gibi.",
    "Antika eşyaları restore etmek, geçmişi yeniden hayat buldurmak çok yaratıcı bir uğraş.",
    "Bir doğa yürüyüşü yapmak ve ormanın derinliklerine inmek, meditasyon gibi bir şey.",
    "Bir dağ evinde sakin bir hafta sonu geçirmek, doğayla baş başa kalmak çok değerli.",
    "Çocuklarla oyun saatleri düzenlemek, onların dünyasına girmek harika bir deneyim.",
    "Bir film setinde çalışmak, sinema dünyasını daha yakından keşfetmek ilham verici.",
    "Bir gönüllü organizasyonunda yer almak, topluma katkı sağlamanın mutluluğunu yaşatıyor.",
    "Bir müzik enstrümanı çalmak, ruhumu dinlendiren ve geliştiren bir yolculuk.",
    "Farklı yemek kültürlerini öğrenmek ve tatmak, dünyayı daha geniş bir bakış açısıyla görmek.",
    "Kendi küçük çiftliğimi kurmak, tarım ve hayvancılıkla uğraşmak hayatımı daha doğal kılar.",
    "Çok dilli bir çevrede yaşamak, dil ve kültürleri birleştirmenin keyfini çıkarmak.",
    "Yapay zekayla ilgili bir araştırma yapmak, teknolojiye dair sorularıma cevap aramak.",
    "Bir denizci olmak ve okyanusta uzun yolculuklar yapmak, özgürlüğün başka bir hali.",
    "Farklı doğal yaşam alanlarını keşfetmek ve koruma çalışmaları yapmak ilham verici.",
    "Dünyanın farklı kültürlerinden geleneksel el sanatlarını öğrenmek, o kültürlere saygı duymayı öğretiyor.",
    "Bir arkeolog gibi kazı yapmak, tarihin izlerini bulmak çok heyecan verici.",
    "Sırt çantasıyla tek başıma bir geziye çıkmak, yalnız başıma keşfe çıkmanın heyecanı.",
    "Bir yaz tatilinde okyanus kıyısında kamp yaparak uyumak, güneşin doğuşunu izlemek çok huzurlu.",
    "Bir çiftlikte organik tarım yaparak sürdürülebilir yaşamı desteklemek harika bir deneyim.",
    "Farklı sosyal medyalarda gezinti yaparak dünyanın dört bir yanındaki yenilikleri takip etmek.",
    "Bir teknoloji şirketinde çalışmak, gelişen dijital dünyaya ayak uydurmanın heyecanı.",
    "Bir sergi açmak ve sanat eserlerimi başkalarına sunmak, yaratıcı ifade biçimimi paylaşmak gibi.",
    "Büyük bir denizaltı araştırma yapmayı hayal etmek, okyanusların derinliklerini keşfetmek.",
    "Bir müzik albümü hazırlamak, duygularımı müzikle ifade etmek harika olurdu.",
    "Bir tatil beldesinde yoga eğitmeni olarak çalışmak, insanlara ruhsal huzur kazandırmak.",
    "Bir araştırma laboratuvarında yeni bilimsel keşifler yapmak, dünyayı daha iyi anlamak.",
    "Bir sinema filmi çekmek, sahneleri tasarlamak, hikayeyi anlatmak heyecan verici bir süreç.",
    "Bir dilin eski yazılarını çözmek, tarihin kaybolmuş dillerine dair bilgileri ortaya çıkarmak.",
    "Bir tasarımcı olarak yeni projelerde yer almak, estetik anlayışımı geliştirmek.",
    "Bir müzik aletinin yapımını öğrenmek, sesin ruhunu daha yakından hissetmek.",
    "Bir fotoğraf makinesi alıp dünyayı farklı açılardan görmek, anları yakalamak çok özel.",
    "Bir festivalde gönüllü olmak, yeni insanlarla tanışmak ve organizasyona katkı sağlamak.",
    "Gün batımını izlerken meditasyon yapmak, ruhumu sakinleştirmek için harika bir yol.",
    "Bir film izlemek ve ardından karakterler üzerine analiz yapmak, sinemayı derinlemesine keşfetmek.",
    "Bir müzik dinlerken notaların derinliğine inmek, müziğin içindeki anlamları görmek.",
    "Bir öğrenci olarak, eğitim hayatım boyunca aldığım derslerle daha fazlasını öğrenmeye devam etmek.",
    "Karmaşık bir problemin çözümü için beyin fırtınası yaparak farklı çözüm yolları keşfetmek.",
    "Bir yelkenli teknesiyle okyanusları geçmek, özgürlüğün tadını çıkararak keşfe çıkmak.",
    "Bir kayak tatilinde dağlara tırmanmak ve hızla kaymak, adrenalini hissetmek çok eğlenceli.",
    "Farklı şehirlere taşınarak her birinin kültürünü öğrenmek ve deneyimlemek harika bir yolculuk.",
    "Bir hayvanat bahçesinde hayvanları gözlemlemek, doğanın çeşitliliğini görmek ve koruma bilinci oluşturmak.",
    "Bir fotoğrafçı olarak manzara fotoğrafları çekmek, doğanın güzelliklerini dünyaya tanıtmak."
    "Sabahları kahvemi içmek günüme enerji katıyor.",
    "Yeni bir iş fırsatını değerlendirmek heyecan verici.",
    "Seyahat etmek yeni yerler keşfetmek beni mutlu ediyor.",
    "Dışarıda yürüyüş yapmak doğayla iç içe olmayı sağlıyor.",
    "Yeni teknolojik gelişmeleri takip etmek beni heyecanlandırıyor.",
    "Gün batımını izlemek içimi huzurla dolduruyor.",
    "Arkadaşlarımla bir kafede sohbet etmek çok keyifli.",
    "Güzel bir gün geçirmek için parkta yürümek harika.",
    "Yeni bir şeyler öğrenmek beni sürekli geliştiren bir şey.",
    "Bir kitapçıda uzun süre vakit geçirmek çok eğlenceli.",
    "Kedimle oynarken çok eğleniyorum.",
    "Çevremdeki insanlarla anlamlı sohbetler yapmak çok değerli.",
    "Dışarıda güzel bir gün geçirmek beni çok mutlu ediyor.",
    "Yürüyüş yaparken doğanın seslerini dinlemek huzur veriyor.",
    "Yeni bir dil öğrenmek için derslere katılmak heyecan verici.",
    "Spor yaparken sağlığımı güçlendiriyorum.",
    "Bir film izlerken tamamen hikayeye dalmak çok eğlenceli.",
    "Denizde yüzmek bana özgürlük hissi veriyor.",
    "Tarih kitapları okumak geçmişi daha iyi anlamamı sağlıyor.",
    "Farklı müzik türlerini keşfetmek eğlenceli bir yolculuk.",
    "Bir arkadaşımı görmek beni mutlu ediyor.",
    "Sabahları sessiz bir ortamda meditasyon yapmak zihnimi arındırıyor.",
    "Kendi bahçemde çalışmak çok rahatlatıcı.",
    "Ailemle birlikte olmak bana huzur veriyor.",
    "Doğayla iç içe olmak ruhumu dinlendiriyor.",
    "Tarihi yerleri gezmek beni geçmişle tanıştırıyor.",
    "Farklı yemekler denemek beni mutlu ediyor.",
    "Gitar çalmak bana büyük bir keyif veriyor.",
    "Kışın karla kaplı ormanlarda yürüyüş yapmak çok heyecan verici.",
    "Yaz tatilinde deniz kenarında vakit geçirmek çok rahatlatıcı.",
    "Sosyal etkinliklerde yer almak bana enerji veriyor.",
    "Bir projeyi başarmak beni çok tatmin ediyor.",
    "Film festivallerine katılmak sinemayı daha çok sevdirmeme yardımcı oluyor.",
    "Çocuklarla vakit geçirmek bana mutluluk veriyor.",
    "Küçük bir tatil kaçamağı yapmak beni çok mutlu ediyor.",
    "Doğada kamp yapmak çok keyifli.",
    "Yeni bir hobi edinmek bana büyük bir heyecan veriyor.",
    "Gitar çalarken kendimi ifade ediyorum.",
    "Yeni teknolojileri öğrenmek beni heyecanlandırıyor.",
    "Güzel bir yemek hazırlamak beni mutlu ediyor.",
    "Yeni bir arkadaş edinmek çok eğlenceli.",
    "Gün batımını izlerken içim huzurla doluyor.",
    "Farklı şehirleri gezmek her zaman heyecan verici.",
    "Bir kitap okurken kendimi başka bir dünyada hissediyorum.",
    "Akşamları yürüyüş yapmak bana sakinlik veriyor.",
    "Deniz kenarında kahve içmek çok keyifli.",
    "Bir sergiye katılmak bana ilham veriyor.",
    "Bir kitap yazmak hayalimi gerçekleştirmek istiyorum.",
    "Tiyatro oyunları izlemek çok öğretici.",
    "Bir şeyler yaratmak beni heyecanlandırıyor.",
    "Sabahları erken kalkmak günümü daha verimli kılıyor.",
    "Doğada yürüyüş yaparken düşüncelerimi toparlıyorum.",
    "Sanat galerilerini gezmek çok öğretici.",
    "Spor yaparken stresten uzaklaşıyorum.",
    "Bir arkadaşımın doğum gününü kutlamak beni mutlu ediyor.",
    "Farklı kültürleri öğrenmek bana geniş bir perspektif kazandırıyor.",
    "Dışarıda yemek yemek bazen çok eğlenceli.",
    "Gitarla yeni bir şarkı çalmak beni çok mutlu ediyor.",
    "Küçük bir köyde zaman geçirmek çok huzurlu.",
    "Bir sinema filmine gitmek eğlenceli bir etkinlik.",
    "Sahilde yürümek çok rahatlatıcı bir aktivite.",
    "Kendimi ifade etmek için resim yapmak çok eğlenceli.",
    "Yaz tatilinde keşfedilecek çok güzel yerler var.",
    "Bir arkadaşımı aramak bana moral veriyor.",
    "Öğrenmek beni geliştiriyor ve mutlu ediyor.",
    "Dışarıda kahve içmek bazen günün en keyifli anı.",
    "Zamanımı verimli kullanarak daha fazla şey yapıyorum.",
    "Gitar çalarken kendimi tamamen kaybediyorum.",
    "Bir şeyler yazmak beni rahatlatıyor.",
    "Yoga yapmak vücudumu dinlendiriyor ve zihnimi arındırıyor.",
    "Akşam yürüyüşlerinde yalnız kalmak çok rahatlatıcı.",
    "Farklı yerler görmek bana çok şey katıyor.",
    "Kışın sıcak bir çikolata içmek çok keyifli.",
    "Bir müzik konserine gitmek beni çok heyecanlandırıyor.",
    "Sosyal medyada yeni içerikler keşfetmek eğlenceli.",
    "Yeni bir fotoğraf çekme tekniği öğrenmek heyecan verici.",
    "Kuşları seyretmek beni dinlendiriyor.",
    "Dışarıda güzel bir akşam geçirmek harika.",
    "Bir tiyatro oyununu izlemek beni çok etkiliyor.",
    "Yeni bir podcast dinlemek bana yeni bakış açıları kazandırıyor.",
    "Çiçekleri sulamak beni rahatlatıyor.",
    "Spor yaparken sağlıklı hissetmek çok güzel.",
    "Arkadaşlarla yapılan bir kahve sohbeti çok eğlenceli.",
    "Yeni yemek tarifleri denemek eğlenceli ve yaratıcı.",
    "Farklı bir kültürden yemekler yemek çok keyifli.",
    "Bir arkadaşımın evinde vakit geçirmek çok eğlenceli.",
    "Doğanın içinde kaybolmak bana huzur veriyor.",
    "Kendime yeni hedefler koymak beni motive ediyor.",
    "Bir filmi tekrar izlemek çok eğlenceli.",
    "Bir kitapçıda gezmek çok keyifli.",
    "Farklı şehirlerdeki mimari yapıları görmek çok ilginç.",
    "Sinemada film izlemek çok eğlenceli bir deneyim.",
    "Gün batımını deniz kenarında izlemek harika.",
    "Doğada yürüyüş yaparken her şey daha güzel görünüyor.",
    "Yeni yerler keşfetmek benim için en büyük zevk.",
    "Sahilde yürüyüş yapmak beni rahatlatıyor.",
    "Bir akşam yemeği hazırlamak bana huzur veriyor.",
    "Bir tatilde keşfedecek çok güzel yer var.",
    "Farklı bir ülkede tatil yapmak heyecan verici.",
    "Bir müzik aleti çalmak beni rahatlatıyor.",
    "Arkadaşlarla yürüyüş yapmak çok eğlenceli.",
    "Gitar çalmak benim için bir terapi gibi.",
    "Çocuklara oyun oynamak çok eğlenceli.",
    "Bir müzik festivali çok eğlenceli bir etkinlik.",
    "Küçük bir tatil kaçamağı yapmak harika.",
    "Sabahları doğanın seslerini dinlemek çok rahatlatıcı.",
    "Bir restoranda yeni yemekler denemek çok keyifli.",
    "Bir yaz tatilinde denize girmek harika.",
    "Bahçemde sebze yetiştirmek çok keyifli.",
    "Farklı yerlerde fotoğraf çekmek çok eğlenceli.",
    "Yeni bir film izlemek her zaman heyecan verici.",
    "Yazın sıcak günlerde dondurma yemek çok eğlenceli.",
    "Bir konser izlemek beni çok heyecanlandırıyor.",
    "Kuşları izlemek doğayla iç içe olmak demek.",
    "Bir tatil planlamak çok heyecan verici.",
    "Yeni bir müzik aleti çalmaya başlamak çok eğlenceli."
    "Sabahları erken uyanmak beni enerjik yapıyor.",
    "Çalışmak beni motive ediyor.",
    "Kahvaltı yapmak günümü güzelleştiriyor.",
    "Sabah koşusu yapmak bana keyif veriyor.",
    "Yeni bir hobim olduğunda çok mutlu oluyorum.",
    "Fotoğraf çekmek beni yaratıcı yapıyor.",
    "Ailemle sinemaya gitmek çok keyifli.",
    "Yeni yerler keşfetmek bana heyecan veriyor.",
    "Tatilde olmak bana huzur veriyor.",
    "Kitapçıda vakit geçirmek beni rahatlatıyor.",
    "Zeytin ağaçlarının arasında yürümek çok huzur verici.",
    "Sabahları güneş doğarken kahvemi içmek hoşuma gidiyor.",
    "Evdeki köşemde kitap okumak bana mutluluk veriyor.",
    "Yaz tatillerinde denize girmek çok eğlenceli.",
    "Yeni yemek tarifleri denemek bana heyecan veriyor.",
    "Akşam yemeğinde sevdiklerimle sohbet etmek beni mutlu ediyor.",
    "Baharda çiçeklerin açmasını izlemek çok keyifli.",
    "Kışın karla kaplı manzaraları görmek büyüleyici.",
    "Sinema salonunda film izlemek harika bir deneyim.",
    "Yeni bir dil öğrenmek beni geliştiriyor.",
    "Yeni bir kitap almak beni heyecanlandırıyor.",
    "Gitar çalmak beni rahatlatıyor.",
    "Yoga yapmak zihnimi arındırıyor.",
    "Dağcılık yapmak bana özgürlük hissi veriyor.",
    "Vize için çalışmak beni geliştiriyor.",
    "Edebiyat kitapları okumak hayal gücümü geliştiriyor.",
    "Kuşları beslemek çok keyifli.",
    "Çevremdeki insanlara yardım etmek beni mutlu ediyor.",
    "Arkadaşlarla bowling oynamak eğlenceli.",
    "Takım çalışması yaparken daha verimli oluyorum.",
    "Resim sergilerini gezmek beni ilham veriyor.",
    "Müzik aleti çalmak bana huzur veriyor.",
    "Zamanı doğru kullanmak bana başarılı hissettiriyor.",
    "Seyahate çıkmak bana yeni bakış açıları kazandırıyor.",
    "Dışarıda yürüyüş yapmak doğayla iç içe olmayı sağlıyor.",
    "Film sahnelerini analiz etmek beni geliştiriyor.",
    "Bahçemde sebze yetiştirmek beni mutlu ediyor.",
    "Spor salonunda çalışmak beni güçlendiriyor.",
    "Doğal ürünler kullanmak sağlığıma iyi geliyor.",
    "Kitap okumak zihnimi açıyor.",
    "Farklı kültürleri tanımak ufkumu genişletiyor.",
    "Yenilikçi projeler üretmek beni heyecanlandırıyor.",
    "Yazar olmak hayalimi gerçekleştiriyor.",
    "Yemek fotoğrafları çekmek çok eğlenceli.",
    "Spor müsabakalarını izlemek heyecan verici.",
    "Çocuklara kitap okumak çok keyifli.",
    "Yeni bir takım oyununa katılmak eğlenceli.",
    "Yelken yapmak denizle barış yapmama yardımcı oluyor.",
    "Bisiklete binmek özgür hissettiriyor.",
    "Günü erken başlatmak bana daha fazla zaman kazandırıyor.",
    "İyi bir kahve içmek günümü güzelleştiriyor.",
    "Çalışma alanımı düzenlemek verimliliğimi artırıyor.",
    "Film izlerken farklı kültürleri görmek çok ilginç.",
    "Ağaçların arasında yürümek doğayla bağ kurmamı sağlıyor.",
    "İyi bir arkadaşla sohbet etmek moral kaynağım oluyor.",
    "Gece yürüyüşleri yapmak sakinleşmemi sağlıyor.",
    "Fotoğraf albümü yapmak hatıraları canlı tutuyor.",
    "Müze gezmek tarihle iç içe olmak harika.",
    "Yalnız kalmak bazen ruhumu dinlendiriyor.",
    "Şehirdeki yeni restoranları keşfetmek çok eğlenceli.",
    "Okul projeleri yapmak beni geliştiriyor.",
    "Yüksek sesle şarkı söylemek enerjimi yükseltiyor.",
    "Güneş batışını izlemek içimi huzurla dolduruyor.",
    "Yeni bir uygulama keşfetmek beni mutlu ediyor.",
    "Dışarıda kamp yapmak doğayla daha yakın olmayı sağlıyor.",
    "Yeni bir gezilecek yer görmek merakımı uyandırıyor.",
    "Çiftlik hayatını deneyimlemek huzur verici.",
    "Yağmurda kitap okumak beni çok rahatlatıyor.",
    "Egzersiz yaparak stresten uzaklaşıyorum.",
    "Vakit geçirmek için yeni bir yer bulmak çok heyecan verici.",
    "Yeni arkadaş edinmek çok eğlenceli.",
    "Kültürel etkinliklere katılmak beni geliştiriyor.",
    "Doğal alanlarda gezmek beni dinlendiriyor.",
    "Sevdiklerimle birlikte olmak bana huzur veriyor.",
    "Tiyatro izlemek çok öğretici bir deneyim.",
    "Zihin oyunları oynamak beynimi keskinleştiriyor.",
    "Çalışırken müzik dinlemek verimliliğimi artırıyor.",
    "Farklı şehirlerdeki mimarileri görmek çok ilginç.",
    "Kalabalık içinde kaybolmak bazen rahatlatıcı.",
    "Yeni arkadaşlar edinmek bana özgüven kazandırıyor.",
    "Çalışma odasını yeniden düzenlemek beni motive ediyor.",
    "Gitar çalarken melodilere kaptırmak çok eğlenceli.",
    "Sanat galerilerine gitmek bana ilham veriyor.",
    "Akşamları meditasyon yapmak ruhumu dinlendiriyor.",
    "Yıldızları izlerken hayaller kurmak büyüleyici.",
    "Çalışma saatlerimi düzenlemek beni daha verimli kılıyor.",
    "Sabah kahvesini yudumlarken sessizliği dinlemek hoşuma gidiyor.",
    "Kitap okurken kendimi kaybetmek harika bir duygu.",
    "Gündelik yaşamda küçük anları kutlamak çok değerli.",
    "Bahçemde oturmak bana huzur veriyor.",
    "Yüksek sesle şarkı söylemek eğlenceli.",
    "Güzel manzaralar görmek içimi ısıtıyor.",
    "Çalışırken not almak bana düzenli olma alışkanlığı kazandırıyor.",
    "Boş zamanlarımda yeni şeyler öğrenmek harika.",
    "Yalnız vakit geçirmek bazen ruhsal olarak iyileştirici oluyor.",
    "Sabahları doğa seslerini dinlemek bana huzur veriyor.",
    "İnsanlarla sohbet etmek sosyal becerilerimi geliştiriyor.",
    "Sosyal medyada yeni içerikler keşfetmek eğlenceli.",
    "Pazarda taze meyve almak beni mutlu ediyor.",
    "Yavaş yürümek bazen içimi rahatlatıyor."
    "Bugün hava çok güzel, dışarıda yürüyüş yapmak istiyorum.",
    "Kitap okumak beni gerçekten mutlu ediyor.",
    "Yeni bir şeyler öğrenmek her zaman heyecan verici.",
    "Doğayla iç içe olmak bana huzur veriyor.",
    "Arkadaşlarımla vakit geçirmekten keyif alıyorum.",
    "Film izlemek bazen çok eğlenceli olabiliyor.",
    "Müzik dinlemek beni rahatlatıyor.",
    "Yemek yapmak ve yeni tarifler denemek hoşuma gidiyor.",
    "Seyahat etmek ve farklı kültürleri keşfetmek istiyorum.",
    "Gülmek ve eğlenmek hayatın en güzel şeylerinden biri.",
    "Güneşin doğuşunu izlemek beni her zaman büyülüyor.",
    "Deniz kenarında yürümek bana iyi geliyor.",
    "Yeni bir dil öğrenmek istiyorum.",
    "Resim yapmak benim için bir tutku.",
    "Dans etmek beni özgürleştiriyor.",
    "Şarkı söylemek içimi rahatlatıyor.",
    "Yazmak benim için bir ifade biçimi.",
    "Problem çözmek beni geliştiriyor.",
    "Yardım etmek beni mutlu ediyor.",
    "Hayal kurmak beni motive ediyor.",
    "Ailemle birlikte olmak benim için çok değerli.",
    "Evde vakit geçirmek bana keyif veriyor.",
    "Bahçemle ilgilenmek beni dinlendiriyor.",
    "Spor yapmak sağlığıma iyi geliyor.",
    "Uyku benim için çok önemli.",
    "Kahve içmek beni canlandırıyor.",
    "Çay keyfi yapmak beni rahatlatıyor.",
    "Doğum günümü kutlamak beni mutlu ediyor.",
    "Yılbaşı benim için özel bir gün.",
    "Bayramlar ailemle bir araya gelmek için harika bir fırsat.",
    "Annemle yemek yapmak çok keyifli.",
    "Babamla sohbet etmek bana ilham veriyor.",
    "Kardeşlerimle oyun oynamak çok eğlenceli.",
    "Arkadaşlarımla sinemaya gitmek istiyorum.",
    "Sevgilimle romantik bir akşam yemeği yemek istiyorum.",
    "Eşimle birlikte seyahat etmek istiyorum.",
    "Çocuklarımla parkta oynamak çok keyifli.",
    "Torunlarımla vakit geçirmek beni çok mutlu ediyor.",
    "Hayvanları çok seviyorum.",
    "Kedimle oynamak beni rahatlatıyor.",
    "Köpeğimle yürüyüş yapmak çok keyifli.",
    "Kuşları seyretmek beni dinlendiriyor.",
    "Balıkları beslemek bana huzur veriyor.",
    "Bitkilerle ilgilenmek beni mutlu ediyor.",
    "Çiçekleri koklamak beni rahatlatıyor.",
    "Ağaçlara tırmanmak çok eğlenceli.",
    "Ormanda yürüyüş yapmak bana iyi geliyor.",
    "Denizde yüzmek beni dinlendiriyor.",
    "Göl kenarında piknik yapmak çok keyifli.",
    "Dağlara tırmanmak beni zorluyor ama keyif veriyor.",
    "Kamp yapmak çok heyecan verici.",
    "Balık tutmak beni sabırlı yapıyor.",
    "Güneşlenmek beni rahatlatıyor.",
    "Yağmurda yürümek beni dinlendiriyor.",
    "Kar yağışını izlemek beni mutlu ediyor.",
    "Gökkuşağını görmek beni heyecanlandırıyor.",
    "Yıldızları seyretmek beni büyülüyor.",
    "Ayı izlemek beni rahatlatıyor.",
    "Gezegenleri öğrenmek beni meraklandırıyor.",
    "Evrenin sırlarını çözmek istiyorum.",
    "Bilim kurgu filmleri izlemek beni heyecanlandırıyor.",
    "Fantastik kitaplar okumak beni büyülüyor.",
    "Tarih öğrenmek beni geliştiriyor.",
    "Coğrafya öğrenmek beni meraklandırıyor.",
    "Felsefe öğrenmek beni düşündürüyor.",
    "Psikoloji öğrenmek beni anlıyorum.",
    "Sosyoloji öğrenmek beni toplumu anlamama yardımcı oluyor.",
    "Ekonomi öğrenmek beni geleceğe hazırlıyor.",
    "Siyaset öğrenmek beni ülkemi anlamama yardımcı oluyor.",
    "Hukuk öğrenmek beni haklarımı korumama yardımcı oluyor.",
    "Tıp öğrenmek beni sağlığımı korumama yardımcı oluyor.",
    "Mühendislik öğrenmek beni yaratıcı yapıyor.",
    "Mimarlık öğrenmek beni estetiğe önem vermeye teşvik ediyor.",
    "Sanat öğrenmek beni güzelliği görmeye teşvik ediyor.",
    "Müzik yapmak beni yaratıcı yapıyor.",
    "Resim yapmak beni duygularımı ifade etmeye yardımcı oluyor.",
    "Heykel yapmak beni üç boyutlu düşünmeye teşvik ediyor.",
    "Tiyatro yapmak beni kendimi ifade etmeye yardımcı oluyor.",
    "Sinema yapmak beni hikayeler anlatmaya teşvik ediyor.",
    "Edebiyat öğrenmek beni kelimelerle oynamaya teşvik ediyor.",
    "Şiir yazmak beni duygularımı ifade etmeye yardımcı oluyor.",
    "Roman okumak beni farklı dünyalara götürüyor.",
    "Öykü yazmak beni kısa ve öz anlatmaya teşvik ediyor.",
    "Deneme yazmak beni düşüncelerimi ifade etmeye yardımcı oluyor.",
    "Makale yazmak beni bilgi vermeye teşvik ediyor.",
    "Çeviri yapmak beni farklı kültürleri anlamama yardımcı oluyor.",
    "Editörlük yapmak beni metinleri düzenlemeye teşvik ediyor.",
    "Yazarlık yapmak beni hayal gücümü kullanmaya teşvik ediyor.",
    "Öğretmenlik yapmak beni bilgi vermeye teşvik ediyor.",
    "Doktorluk yapmak beni insanlara yardım etmeye teşvik ediyor.",
    "Mühendislik yapmak beni sorunları çözmeye teşvik ediyor.",
    "Mimarlık yapmak beni güzel yapılar inşa etmeye teşvik ediyor.",
    "Sanatçılık yapmak beni yaratıcı olmaya teşvik ediyor.",
    "Müzisyenlik yapmak beni müzikle insanlara dokunmaya teşvik ediyor.",
    "Oyuncu olmak beni farklı karakterlere bürünmeye teşvik ediyor.",
    "Yönetmen olmak beni hikayeler anlatmaya teşvik ediyor.",
    "Yazar olmak beni kelimelerle dünyalar yaratmaya teşvik ediyor."
]




tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)  #metinler üzerindeki kelime frekanslarını öğren
total_words = len(tokenizer.word_index) + 1  # toplam kelime sayisi
#print(total_words)  #1461 kelime mevcut


#ngram dizileri oluşturma ve padding uygulama
input_sequences = []
for text in texts:
    # metinleri kelime indexerine çevirme
    token_list = tokenizer.texts_to_sequences([text])[0]

    # her metin için input dizisi oluşturma
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)
        #print(n_gram_sequence,"\n")  # çümleleri n gram modelleri halinde sayısal ifadelendirmesine dönüştürüldü

# en uzun diziyi bulup tüm dizileri aynı uzunluğa getirme
max_sequence_length = max(len(x) for x in input_sequences)
#print(max_sequence_length)  # 27

#dizilere padding işlemi uygulayarak aynı uzunlukta olmasını sağlamak
input_sequences = pad_sequences(input_sequences, maxlen = max_sequence_length, padding="pre")
#print(input_sequences) # aynı uzunlukta olmaları için aynı uzunlukta olana kadar başına 0 ekledi


# x ve y 
X = input_sequences[:,:-1]  # tüm çümlelerin son kelimelerini almıyorum ben tahmin yaptırcağım ona
Y = input_sequences[:,-1]   # tüm çümlelerin son kelimesini alıyorum y ye eşitliyorum


# one hot encoding işlemi yapıyorum çünkü kelimelerin temsil ettiği sayılar çok büyük veya çok küçük bunları küçük sayılara sıkıştırcam  bütün sayıları matrise çevirdi binary olarak ifade etti sadece 
Y = tf.keras.utils.to_categorical(Y, num_classes = total_words) # kelimenin temsil ettiği sayı 1 oldu geri kalan sayılar 0 oldu her kelime için uygulandı bu işlem




#lstm modelini oluşturulması


model = Sequential()

#embedding
model.add(Embedding(total_words, 50, input_length = X.shape[1]))  #embedding katmanı içeri kelime sayısını, boyut sayısını ve input uzunluğunu veriyorum
#lstm
model.add(LSTM(100, return_sequences = False)) #  sadece son cıktıyı döndürmesi için kullanılıyor return_sequences ben bunu istemediğim için false yapıyoruz
#ilk parametrede 100 noronlu olduğunu söylüyorum

#output
model.add(Dense(total_words, activation = "softmax"))  # ütün kaleimeli veiryoruz burda ve aktiackson fonkiyonunda binary kalsication yapmadığımız için softmax fonksiyonunu kullancaz

#model compile
model.compile(optimizer = "adam", loss = "categorical_crossentropy", metrics = ["accuracy"]) #adaptipmoment

#model.training
model.fit(X,Y,epochs = 150, verbose = 1) #verbose 1 olunca trainingi bize göstericek



def generate_text(seed_text, next_words):
    for _ in range(next_words):
        # girdi metminini sayısal verilere dönüştürmem lazım
        token_list = tokenizer.texts_to_sequences([seed_text])[0]


        #padding
        token_list = pad_sequences([token_list], maxlen = max_sequence_length - 1 ,padding = "pre")

        #prediction 
        predicted_probabilities = model.predict(token_list, verbose=1)

        #en yüksek olasılığa sahip kelimenin indexini bulalım
        predicted_word_index = np.argmax(predicted_probabilities, axis=1)

        #tokenizer ile kelime indexsinden asıl kelimeyiyi bul
        predicted_word = tokenizer.index_word[predicted_word_index[0]]

        #tahmin edilen kelimeyi seed texte ekle
        seed_text = seed_text + " " + predicted_word

    return seed_text


seed_text = "akşamları "
print(generate_text(seed_text, 6))